### PR TITLE
Allow REST libraries to override the major version number

### PR DESCRIPTION
**Pull request by jskeet**
(Review each commit separately)

### CODE REVIEW

**Comment by jskeet** [comment]
Not sure why it's failing to build... on it.

**Comment by jskeet** [comment]
Ah, it's the test code - for some reason VS hadn't mentioned that before. Fixing.

**Comment by jskeet** [comment]
(Fixed in the third commit - the second commit would still be broken, but we'll never need to go back to that...)

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
