### PR TITLE
chore: Update to .NET 6

### PR DESCRIPTION
**Pull request by jskeet**
(Not ready for review yet.)

### CODE REVIEW

**Comment by jskeet** [comment]
This will fix #495 eventually, but we need to move everything off GAX v3 first.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
I'm testing this locally with Bazel (I'd forgotten to update the hash) - once it's working, I'll merge. We'll probably want to wait until next week to do a release though. (And I'm hoping to merge the "no unit tests" before then too.)

**Comment by jskeet** [comment]
Looks like it's working with Bazel - merging.

**Pull request merged**
