### PR TITLE
Add the remainder of the Request class generated for methods

### PR DESCRIPTION
**Pull request by jskeet**
The next step will be to generate the Data classes properly so we can access those for both the "body" parameter and the response type for request classes.

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by amanda-tarafa** [comment]
Travis is failing though.

**Comment by jskeet** [comment]
That's an odd failure. Restarted... we'll see what happens.

**Comment by jskeet** [comment]
Looks okay now. Merging.

**Pull request merged**
