### PR TITLE
More REST generator changes

### PR DESCRIPTION
**Pull request by jskeet**
Review one commit at a time. This is just fixing up the base request, really - although I expect a lot of it may be useful elsewhere later.

### CODE REVIEW

**Comment by chrisdunelm** [comment]
One slightly nitty point... There is a change to the white-space formatter but no test for it; it a test attribute with args could be added that would be good :)

**Comment by jskeet** [comment]
Yup, good point - will add that as an extra commit.

**Comment by jskeet** [comment]
@chrisdunelm: See the new last commit. It's a bit odd, to be honest...

**Review by chrisdunelm — APPROVED** [review]
Yes, I see what you mean.
There may be a more elegant solution, but as you say, this works for now :)
LGTM

**Comment by jskeet** [comment]
Cool - will wait for Amanda to look tomorrow before merging, mostly for the REST aspect.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
