### PR TITLE
Remove old targets from generated REST packages

### PR DESCRIPTION
**Pull request by jskeet**
Fixes https://github.com/googleapis/google-api-dotnet-client/issues/2078

We need to work out whether we're happy to merge this now, or wait until we're going to do a new minor version of the support packages.

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM.

**Comment by jskeet** [comment]
Great. Will wait until we've worked out *when* we want to merge this.

**Comment by amanda-tarafa** [comment]
It'd be nice to add the following so that the projects build on VS 2022

```
<ItemGroup Condition="'$(TargetFramework)'=='net45'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="1.0.2" PrivateAssets="All" />
</ItemGroup>
```

**Comment by jskeet** [comment]
@amanda-tarafa: I've added a final commit for that. PTAL.

**Review by amanda-tarafa — APPROVED** [review]
LGTM still!

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
